# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XV8enZ4jneJ5AUQIC7G-NkvdciA4bteo
"""

i = 1
while i <= 20:
    if i % 2 == 0:
        print(i, end=" ")
    i += 1